# Generated by Django 5.0.6 on 2026-06-18 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demandeur_nom", models.CharField(max_length=150)),
                ("demandeur_email", models.EmailField(max_length=254)),
                (
                    "type_demandeur",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("organisation", "Organisation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom_manifestation", models.CharField(max_length=200)),
                ("nb_personnes", models.PositiveIntegerField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("raison_refus", models.TextField(blank=True, null=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "prix_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes",
                        to="salles.salle",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de réservation",
                "ordering": ["-date_soumission"],
            },
        ),
        migrations.CreateModel(
            name="SuiviCles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_remise_prevue", models.DateTimeField(blank=True, null=True)),
                ("date_remise_reelle", models.DateTimeField(blank=True, null=True)),
                ("paiement_effectue", models.BooleanField(default=False)),
                (
                    "montant_paye",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "date_restitution_prevue",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "date_restitution_reelle",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cles_rendues", models.BooleanField(blank=True, null=True)),
                ("rappel_envoye", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivi",
                        to="reservations.demandereservation",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suivis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi des clés",
            },
        ),
        migrations.CreateModel(
            name="ReservationMateriel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("confirme", "Confirmé"), ("annule", "Annulé")],
                        default="confirme",
                        max_length=20,
                    ),
                ),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="salles.appareil",
                    ),
                ),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiels",
                        to="reservations.demandereservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel réservé",
                "unique_together": {("demande", "appareil")},
            },
        ),
    ]
