# Generated by Django 5.0.6 on 2026-06-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appareil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "prix_location",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Appareil",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                ("surface_m2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("capacite_min", models.PositiveIntegerField()),
                ("capacite_max", models.PositiveIntegerField()),
                ("est_payante", models.BooleanField(default=False)),
                ("a_gardien", models.BooleanField(default=False)),
                (
                    "prix_heure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Salle",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="AppareilSalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_louable", models.BooleanField(default=False)),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salles",
                        to="salles.appareil",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appareils",
                        to="salles.salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil en salle",
                "unique_together": {("salle", "appareil")},
            },
        ),
    ]
